# Generated by Django 6.1.1 on 2026-10-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='owner',
            new_name='seller',
        ),
    ]
